Add language about our services
2i2c-org/2i2c-org.github.io pull request #298
Opened 2024-08-22 21:35 UTC by choldgraf

This does two main things:

- Adds language + a link on our home page about us providing consulting services
- Adds language to our platform page about what kinds of services we provide, with another CTA to the `join` page

@Gman0909 is this the kind of thing you had in mind?

2024-08-23 08:09 UTC, Gman0909 requested changes
I think this is looking good, besides the adjustments I suggested. I would also maybe run the new language by @jmunroe as he was the one who originally suggested we highlight our consultancy services on our brochure site.

2024-08-23 08:09 UTC, Gman0909 commented on content/_index.md
> -        We serve **over 90 communities across the globe** with **over 7000 active users** that are dedicated to creating and sharing knowledge. See [our community impact stories](/communities) for in
In dark mode, this block looks excessively cramped, mainly due to the solid white bar containing the logos. Ideally we should be using reversed logo assets to avoid the white bar effect:

![image](https://github.com/user-attachments/assets/4e637aa6-1b8b-48b2-9772-7474f15b5ef9)

2024-08-23 08:09 UTC, Gman0909 commented on content/platform/_index.md
> +              <p class="card-text px-0">Our open infrastructure team contributes to open source projects to enhance the functionality of your service.</p>
Suggest: "Our infrastructure team is an active contributor to the open source community, ensuring our hubs, and your service, always benefit from the latest developments"

2024-08-23 08:09 UTC, Gman0909 commented on content/platform/_index.md
> +      title: Standard hub features
I suggest looking at the visual hierarchy of headings here: Sign-in is a sub-section of "Standard hub features" but visually they use the same heading level. Increasing our H1s or decreasing our H2's should help make the hierarchy clearer. Eyeballing it, I think the "Compute" heading below is using the appropriate size. 

![image](https://github.com/user-attachments/assets/598de1db-f103-4a5a-8131-c7f13e333164)

You can see the difference in size here:

![image](https://github.com/user-attachments/assets/1d623521-fca9-4799-b394-5d0f4ba570ec)

2024-08-29 08:27 UTC, jnywong commented on content/_index.md
> -        We serve **over 90 communities across the globe** with **over 7000 active users** that are dedicated to creating and sharing knowledge. See [our community impact stories](/communities) for in
Colour-inverted logos resolved in https://github.com/2i2c-org/2i2c-org.github.io/pull/298/commits/4386cee3f482e368024c6aebea44692f21e25eb4

2024-08-29 08:36 UTC, jnywong commented on content/platform/_index.md
> +      title: Standard hub features
The "Sign-in" section and the "Compute" section use different block styles in the Hugo Blox theme and therefore yields differently sized H1s.

I've taken a quick look at the CSS styling and it's not obvious to me how to fix this, so I am inclined to let this one go for now.

2024-08-29 08:37 UTC, jnywong commented on content/platform/_index.md
> +              <p class="card-text px-0">Our open infrastructure team contributes to open source projects to enhance the functionality of your service.</p>
Resolved in https://github.com/2i2c-org/2i2c-org.github.io/pull/298/commits/4386cee3f482e368024c6aebea44692f21e25eb4

2024-08-29 08:40 UTC, jnywong approved these changes
lgtm

2024-09-04 12:24 UTC, jmunroe approved these changes
All good to go.

2024-09-04 19:44 UTC, merged

2024-09-04 19:44 UTC, choldgraf commented
thanks for the feedback all - let's keep iterating on this content as we learn more